#!/usr/bin/env python

import sys
import yaml

from bulletml import BulletML, bulletyaml

def main(argv):
    if not argv:
        raise SystemExit("Usage: %s filename ..." % sys.argv[0])

    for filename in argv:
        print "# Loading", filename
        print yaml.dump(BulletML.FromDocument(open(filename, "rU")))

if __name__ == "__main__":
    main(sys.argv[1:])
